chore: adding isElementRendered
CrispusDH/oi-grease pull request #1
Opened 2022-10-18 13:21 UTC by igorblyzn

2022-10-18 13:22 UTC, igorblyzn commented
@CrispusDH could you review please

2022-10-19 08:09 UTC, CrispusDH commented on API.md
> +check is element visible after timeout
`check is element visible after timeout`
there is a difference between `visible` and `rendered` 
what exactly do you check?
as I see from code you check visibility
might be better to name that function differently
would leave it to you :D

2022-10-20 07:16 UTC, CrispusDH requested changes

2022-10-20 07:16 UTC, CrispusDH commented on src/predicates.ts
> +const checkVisibility = async (
let's put it inside `isElementVisible` as `const` variable with naming `isVisible` or smth

2022-10-20 07:16 UTC, CrispusDH commented on src/predicates.ts
> +      return await checkVisibility(page, selector);
`await` here is redundant

2022-10-20 07:16 UTC, CrispusDH commented on src/predicates.ts
> +    error.message = `Element with ${selector} is not visible. Because of: ${error.message}`;
what if user put `timeout`, do you think we should not add it to error message?

2022-10-24 07:29 UTC, CrispusDH approved these changes

2022-10-24 07:30 UTC, merged